baseURL = 'https://mmozgovoy.dev' # https://rg-software.github.io/homepage/'
languageCode = "en"
defaultContentLanguage = "en"
title = 'The Pro Amateur'
theme = "hugo-coder"
paginate = 100
rssLimit = 40
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

# [params.utterances]
#  repo = "rg-software/homepage"
#  issueTerm = "pathname"
#  # label = "" # https://utteranc.es/#heading-issue-label # optional
#  theme = "github-light"

# [markup.highlight]
# noClasses = false

[params]
  author = "Maxim Mozgovoy"
  # license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
  info = ["Researcher and software developer"]
  customCSS = ["css/academicons.min.css", "css/admonitions.css"]
  description = "The Home of Maxim Mozgovoy"
  keywords = "blog,developer,personal,homepage"
  avatarURL = "misc/dizzy-dtr.gif"
  favicon_32 = "misc/favicon.png"
  rtl = false
  colorScheme = "auto"

  #gravatar = "john.doe@example.com"
  #dateFormat = "January 2, 2006"
  #since = 2019
  # Git Commit in Footer, uncomment the line below to enable it
  #commit = "https://github.com/luizdepra/hugo-coder/tree/"
  # Hide the toggle button, along with the associated vertical divider
  hideColorSchemeToggle = false
  # Series see also post count
  maxSeeAlsoItems = 5

  customJS = []
  customRemoteJS = []


[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 5
  url = "mailto:mozgovoy@u-aizu.ac.jp"

[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 7
  url = "https://www.facebook.com/maxim.mozgovoy.92/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 8
  url = "https://www.linkedin.com/in/maxim-mozgovoy/"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 10
  url = "https://github.com/rg-software"

[[params.social]]
  name = "Youtube"
  icon = "fa fa-youtube fa-2x"
  weight = 12
  url = "https://www.youtube.com/channel/UCyuC02Va7Wr-j-9X9Tfy1vA/"

[[params.social]]
  name = "Stack Exchange"
  icon = "fa fa-stack-exchange fa-2x"
  weight = 20
  url = "https://stackexchange.com/users/15050179/rg-software/"

[[params.social]]
  name = "Google Scholar"
  icon = "ai ai-google-scholar-square ai-2x"
  weight = 23
  url = "https://scholar.google.com/citations?user=XlMbkRsAAAAJ/"

[[params.social]]
  name = "LJ"
  icon = "fa fa-pencil fa-2x"
  weight = 26
  url = "https://rg-software.livejournal.com/"

[[params.social]]
  name = "Habr"
  icon = "fa fa-square-h fa-2x"
  weight = 27
  url = "https://habr.com/users/rg_software/"

[[params.social]]
  name = "RSS"
  icon = "fa fa-rss fa-2x"
  weight = 28
  url = "posts/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[[params.social]]
  name = "CC"
  icon = "fa fa-cc-cc"
  weight = 35
  url = "https://creativecommons.org/licenses/by/4.0/"

[[params.social]]
  name = "BY"
  icon = "fa fa-cc-by"
  weight = 40
  url = "https://creativecommons.org/licenses/by/4.0/"


[[menu.main]]
  name = "Blog"
  weight = 10
  url  = "posts/"
  
[[menu.main]]
  name = "Books"
  weight = 20
  url  = "books/"

[[menu.main]]
  name = "Papers"
  weight = 30
  url  = "papers/"

[[menu.main]]
  name = "Software"
  weight = 35
  url  = "software/"

[[menu.main]]
  name = "CV"
  weight = 40
  url = "cv/"

[[menu.main]]
  name = "ZX"
  weight = 45
  url = "zx/"

[[menu.main]]
  name = "About"
  weight = 50
  url = "about/"

[markup]
  [markup.highlight]
    style = "pastie"


[params.goatCounter]
  code = "proamateur" # Account page: https://[code].goatcounter.com


[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.goTemplates]
    allowActionJSTmpl = false
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']


# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]
