---
title: "My First Post"
date: 2021-09-02T14:56:20+09:00
draft: false
---

:source-highlighter: rouge
:rouge-css: style
:rouge-style: pastie
:icons: font

{{< notice tip >}}I'm giving a tip about something.{{< /notice >}}
// note tip example question info warning error

[TIP]
It's possible to use Unicode glyphs as admonition icons.

icon:area-chart[] note icon


ROUGIFY THEMES

[ditaa]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....


icon:file[] And a file icon

icon:comment[] This is a comment icon

icon:sticky-note[] note icon

icon:pie-chart[] note icon

icon:tex[] note icon


Base16
BlackWhiteTheme
cdesc-Themes.ri
Colorful
Github
Gruvbox
IgorPro
Magritte
Molokai
Monokai
MonokaiSublime
Pastie
ThankfulEyes
Tulip


begin
[source,xml]
----
<section>
  <title>Section Title</title> <!--1-->
</section>
----

<1> The section title is required.

end


WARNING: Bla-bla!


blabla bla bla
and once again

*blabla*
bla!
again
try now

NOTE: There are things to note! +
More things to note! +
Even more things to note!


here comes milk

NOTE: Remember the milk!

here ends milk

[source,ruby]
----
puts "Hello, World!"
puts "Hello, World!" <1>
puts "Hello, World!" <2>
----
<1> Something here
<2> Something else here


bbb
:smiley_cat:

[IMPORTANT] 
==== 
*Feeding the Werewolves* +
While werewolves are hardy community members, keep in mind the following dietary concerns. They are allergic to cinnamon.
====


. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.


```java,linenums
public static void main( String args[] ) {
    System.out.println("Foobar!"); <1>
}
```
<1> Print something


[fa fa-github fa-2x]

fa fa-github fa-2x

adjust: blabla

ADJUST: blabla


