---
title: "💡 On Free Will"
date: 2025-07-03T10:10:20+09:00
draft: false
---

:source-highlighter: rouge
:rouge-css: style
:rouge-style: pastie
:icons: font

The problem of free will is one of those ever-tempting, evergreen topics that one simply cannot avoid sooner or later. I vividly remember my first realization (somewhere in my teens, I guess) that the laws of physics are deterministic, so our lives are hardly more "free" than trajectories of balls on a pool table. Later, I was pleased to learn that quantum mechanics suggests our world is in fact stochastic, so human destinies are not really cast in stone.

Recently I finally found some time to read more about views on this matter, and update my own intuitions. I don't want to retell https://en.wikipedia.org/wiki/Free_will[Wikipedia] here; let me focus instead on the points that are valuable and meaningful to me personally.

== Intuitive approaches

I think we all share a similar intuitive model of free will, which is technically close to the concept of https://en.wikipedia.org/wiki/Libertarianism_(metaphysics["metaphysical libertarianism"]. The future is not defined, there are branches on the way. By exercising our will in turning points, we force some branches to take over, or at least, increase their likelihood. This is a somewhat mystic and ill-defined process, but at least it's safe to say we feel we deserve praise for our successes, and accept responsibility for failures. We generally believe that people who do bad things deserve punishment, because it was their choice to do the bad thing.

Free will (or, at least, some of its facets) is commonly defined in a way that agrees with this notion. For example, Cambridge Academic Content Dictionary https://dictionary.cambridge.org/dictionary/english/free-will[defines] free will as _"the ability to act and make choices independent of any outside influence"_. However, a more careful look shows that one might agree with this wording and still believe in the physically deterministic model of human behavior. Even if human is a deterministic machine, it is still _the human_ who chooses between different possible courses of actions. Therefore, believing in free will under this notion is nothing more than believing that a machine can act autonomously.

The primary issue with the intuitive model is that it is hardly compatible with scientific views on reality. It suggests that a certain mystic "willpower" is able to change the course of history. Libertarianism nicely describes how we _perceive_ our freedom, but taken seriously it looks like a call to defy the laws of physics and to presume that we, in a sense, exist outside the world of molecules, cars, plants, and frogs. They can't shape history at their will; we can.

A more sober approach would be to accept that https://www.amazon.co.jp/We-Are-Our-Brains-Alzheimers/dp/0241003725["we are our brains"], and that our wetware-powered decision making system is as physical an object as molecules, cars, plants, and frogs. This understanding is surprisingly old and can be traced back at least to Stoics and Epicureans. To reconcile physics with our intuitive libertarianism is the challenge.

== No Free Will

I am slightly embarrassed to acknowledge that I lifted two pretty mediocre (as it turned out) books up on my reading list. It is quite natural to pay more attention to the work of the authors you like, but here this strategy did not work very well.

Sam Harris's essay-sized book https://en.wikipedia.org/wiki/Free_Will_(book)["Free Will"] is a fairly straightforward account of what science thinks about decision making, followed by an unsurprising conclusion: there is no place for free will in this purely physical world of chemical reactions and electrical charge transfer. My issue with this book is that it really adds nothing to the debate. Harris could have simply quoted someone like Spinoza, adding that modern neuroscience endorses such a view. I suspect for a celebrity like Harris, who knows that anything he writes will be heard, there is little reason _not_ to put his two cents in.

Another book in this duo is Robert Sapolsky's https://en.wikipedia.org/wiki/Determined:_A_Science_of_Life_Without_Free_Will["Determined. A Science of Life without Free Will"]. I regret to say that this book is not better: it is mediocre, hardly original, and bloated.

However, both these books provide a very accessible intro into a scientifically-backed "no free will" position. There are no surprises there for anyone with a background in natural sciences. Physics, chemistry, and neuroscience leaves literally no room for anything like libertarian free will. Looking from this side, it is completely natural to declare free will an illusion, and it is very hard to find reasonable counter-arguments.

One tempting decoy is quantum mechanics. For some reason, some people believe that non-deterministic universe is somehow more conducive for free will. Sir Roger Penrose even https://en.wikipedia.org/wiki/Shadows_of_the_Mind[considers] quantum processes a foundation of human thinking. Now, this is very unconventional view, but even without "quantum thinking", non-deterministic world is an attractive idea. As I mentioned before, I was pleased to learn that our world is likely stochastic.

Unfortunately, a harder look shows that nondeterminism is merely _metaphysically pleasant_. We like the thought that our future is not sealed. However, it is not sealed thanks to "quantum dice", not free will. Imagine a world where sometimes a true random number is produced to make a choice. Imagine another world, where a random number is taken from a precomputed list of true random numbers. Is there any conceivable difference between these worlds for their inhabitants?

== Compatibilism

According to Harris, _"Today, the only philosophically respectable way to endorse free will is to be a compatibilist—because we know that determinism, in every sense relevant to human behavior, is true."_ Then he continues: _"However, the 'free will' that compatibilists defend is not the free will that most people feel they have."_

I think this statement is quite accurate, but Daniel Dennett does not think so. I found his https://www.samharris.org/blog/reflections-on-free-will[review] of Harris's book pretty condescending, and Harris https://www.samharris.org/blog/the-marionettes-lament[certainly feels this way]. Being a compatibilist, Dennett criticizes Harris's views, which is not surprising. What I found surprising at time is his somewhat irritated attitude, making his response quite an embarrassing reading. However, after reading more of Dennett, I softened to his reaction. He literally spent decades writing on this topic just to get back to square one with Harris's book. Successfully or not, Dennett tried to address the arguments of "hard scientists", so there is no surprise he is not keen to do it all over again.

It is somewhat funny that Dennett, in turn, is a favorite target for thrashing in Sapolsky's book. Sapolsky's assistant here is a "crack baby", who is born to an antisocial drug abuser, has no capacity to become anything decent, and thus should allegedly demonstrate nonexistence of free will. I think this is a pretty low kind of straw man argument, which at best shows that not everyone is free to the same extent.

Whether we agree with Dennett or not, his book https://mitpress.mit.edu/9780262527798/elbow-room/["Elbow Room"] at least provides a far more nuanced treatment of the matter at hand. I'd say his views are actually not that far from that of free will deniers, but _nuance_ is what matters here. I am not even sure which camp I should assign myself to now! My intuition is that Harris is right regarding the "most people's" expectations of a free will concept (Dennett believes there is no evidence for such claims). I think the compatibilist notion can be made convincing, but it is not really what comes to mind naturally.

Compatibilist free will is merely an idea that we are able to act autonomously to achieve our goals. One may note that, say, a bee also acts autonomously to achieve its goals. My understanding of the compatibilist perspective is that the difference between us and bees is in degrees of freedom. An elevator can go only up and down; a car can move left and right, back and forth; a plane can move in a 3D space. Similarly, to execute free will (whatever it means) one needs a sophisticated decision making system that can efficiently make use of the available information, and actual capacity to implement planned decisions. A bee knows how to to several things and is able to switch between action patterns as a response to external stimuli. We can do better, and what is more important, we can expand the limits of our free will. In a sense, free will of a baby is much more limited that free will of a well-adapted, skillful and educated adult. We have free will because the actions we take are _our_ actions. If we accept that "we are our brains", then anything that comes from our brains is "freely chosen".

Interestingly, this approach has little to do with determinism or quantum mechanics. Under this definition, the concept of free will is equally applicable to a deterministic autonomous agent in a deterministic world, a nondeterministic autonomous agent in a nondeterministic world or any other combination of them. In either case, the agent does not possess the complete information about its environment and necessarily relies on heuristic or randomization ("real" or "pseudo", which makes no practical difference).

If _this_ kind of free will is not good enough, Dennett continues, then _what_ kind of free will is worth wanting? Our brain is evolved to get us what we want, it is able to adapt and adjust our behavior, it is able to learn from experience and from the experience of others. It is not really possible to have a brain that defies the laws of nature, so we have to accept its limitations of a physical object. However, what kind of theoretically possible free will are we robbed of? 

== On Moral Responsibility

Nearly every book on free will devotes at least some part (often a substantial part) to the question of moral responsibility. If there is no free will, should we punish people for their crimes if they simply did what their brains dictated them to do? I find this discussion somewhat contradictory: the phrase "should we" implicitly presumes free will; if there is no free will, there is no choice to make in "should we". The writer proposes a certain policy because his brain dictates so, and the policy is accepted or rejected due to the decisions made by other brains, having no free will either.

Having said that, I'd note that our brains can solve optimization problems "out of the box"; we don't even need free will for it. Suppose we punish one group, do not punish another group, and then compare the outcomes to decide which policy is more efficient. Interestingly, some authors (e.g., https://en.wikipedia.org/wiki/Derk_Pereboom#Free_will[Derk Pereboom]) who don't believe in free will, still believe that people are morally responsible for their actions.

I take this topic somewhat lightly. Sapolsky believes that we should heal and correct rather than punish. I am fine with it: if we can correct dangerous behavior, let it be so. I am not vengeful. If someone cannot control themselves, but can do it with the help of appropriate medicine, let it be medicine rather than prison. On the other hand, as long as science gives us no better options, we'll have to resort to prisons, whether they are morally fair or not.

== Summing Up

I think my intuition is that Harris is right when he says that compatibilist free will is not the free will we typically imagine. The free will we imagine is a physically impossible and ill-defined libertarian free will. What we have is a Turing-complete bag of abilities that we use to navigate and leverage our environment to our advantage. The illusory free will as we perceive it is a part of our decision making system. The illusion of free will is crucial to us: if we don't believe it, we indeed lose the ability to make good decisions. If I don't believe I can make a choice, I indeed cannot make it.

Can we argue that compatibilist free will is as good as our illusion? Well, I guess so. I don't think it is immediately intuitive, but the concept of free will is itself a not well-defined one. Searching for free will in our brain is like searching for a soul. We are seeking a "thinking self", but only see a bunch of neurons. If free will is the ability to come up with possible decisions, evaluate them and choose the one to take upon reflecting, then free will is right here, as we are obviously capable of doing it. This system is able to act autonomously in a nondeterministic environment, and can employ all kind of tools including heuristics and randomicity.

Under this definition, free will is not like an "on/off" switch. It can be pronounced to a different degree, reflecting the sophistication of a particular decision making system. Our brains, clearly, do have limitations. Anything man-made is constructed as a hierarchical system, minimizing the number of connected components on every level of hierarchy. We can "grok" stuff that contains maybe 5-10 connected components. Larger systems have to be created from black-box components, so we don't have to care about their internal structure. We can create things like recurrent neural networks and prove they work, but I think there are severe constraints for "explainable" AI in such systems. A system that consists of numerous connected components is just too much for us to comprehend. On the other hand, we are good at "going meta": we can realize that something is not comprehensible, and find our way around limitations.

I am somewhat puzzled with common arguments against free will that explore the idea of "tapping" into the system. For example, a commonly cited https://en.wikipedia.org/wiki/Benjamin_Libet#Volitional_acts_and_readiness_potential[Libet's experiment] shows that a decision can be detected in the brain much earlier than we recognize it. Well, how could it be otherwise? Information does not flow instantly. If a decision making module is somehow separated from a decision evaluation module, what can we prove by sniffing the connection between them? Likewise, numerous lab experiments and thought experiments show how to disrupt decision making, how to bend one's free will to follow experimenter's objective. Again, how could it be otherwise? Any system can be exploited and manipulated, there is no doubt about it. The proponents of such arguments seem to accept only perfect, fool-proof systems.

We are likely living in a true nondeterministic environment (as quantum mechanics suggests). Making no conceivable difference, it is somewhat "metaphysically pleasant". We operate in this environment using our autonomous decision making system. Its decisions are _our_ decisions, because it is a part of us. Are we at its mercy? In a sense; but we are also slaves to our stomach and other organs having minds of their own. It seems there is little more than that here, and the question of the existence of free will boils down to whether we buy its compatibilist definition.

Harris's book cover shows a marionette crossbar and strings attached to the letters "F-R-E-E-W-I-L-L". There is a crossbar, there are strings, but no puppeteer. This is an interesting metaphor: do marionettes without puppeteer have free will? Coincidentally, one of my favorite childhood books, https://azbooka.ru/books/ploshchad-kartonnykh-chasov-pwpe[The Square of Cardboard Clocktower] had the answer to this very question. The demigod of the book, a hatmaker, created a whole city of cardboard, inhabited by cardboard people. He neglected to cut off strings behind the back of every person, seeing no trouble in that. Cardboard people lived happily for a while, until a wandering rogue came upon the city and started pulling strings to his advantage. At the end of the book the hatmaker saves the day, sends away the rogue, visits every single person in the city, and _binds strings attached to a head with strings attached to arms_, so that _"head and arms listen to each other"_.

The cardboard people are still puppets, but in this book they have free will because their strings are attached in the right way.
